### ISSUE TITLE
After adding a magnet link to the docker version, the system hangs

### ISSUE THREAD

**Issue by ystyle** [varbhat/exatorrent#41] opened 2021-09-02 06:51 UTC
docker-compose.yaml
```yaml
version: '3.1'

services:
  torrent:
    image: ghcr.io/varbhat/exatorrent:latest
    restart: always
    volumes:
      - ${HOME}/Downloads:/exa/exadir
    ports:
      - 5000:5000
      - 42069:42069
```
```shell
docker-compose up -d
```
operation:
1. add a new admin user
2. logout and login new user  and disabled adminuser
3. add magnet link

magnet link： 
```
magnet:?xt=urn:btih:787b951c9635c58928260e02a01e2b5434d8bb13&tr=http://tracker.36dm.com:2710/announce
```

system info:
```shell
                   -`                    ystyle@Archlinux 
                  .o+`                   ---------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: XPS 13 7390 
               `+oooooo:                 Kernel: 5.13.12-arch1-1 
               -+oooooo+:                Uptime: 7 days, 4 hours, 18 mins 
             `/:-:++oooo+:               Packages: 1627 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.8 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.22.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: Breeze 
       -osssssso.      :ssssssso.        Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
      :osssssss/        osssso+++.       Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: terminator 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-10710U (12) @ 4.700GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel Comet Lake UHD Graphics 
 `++:.                           `-/+/   Memory: 7627MiB / 15695MiB 
 .`                                 `/
```

```
 ystyle@Archlinux ~/Downloads  id
uid=1000(ystyle) gid=1000(ystyle) groups=1000(ystyle),972(docker),998(wheel)
```

cpu: 200%(total 600%) Memory: 100% (16g ram and 20G swap)

**Comment by varbhat** [comment] 2021-09-02 06:55
@ystyle ,

After adding the magnet , can you please go to stats > device stats and please observe it?

also , if possible can you please send those stats(probably as screenshot) ?

**Comment by varbhat** [comment] 2021-09-02 07:01
@ystyle ,

Do it please. Also, can you please run not in Docker to see if problem exists ?(use official binary from releases) I want to know whether this problem is related to docker

**Comment by ystyle** [comment] 2021-09-02 07:16
log 
```shell
 ystyle@Archlinux  ~/Code/Docker/exatorrent  docker-compose logs -f
Attaching to exatorrent_torrent_1
torrent_1  | 
torrent_1  | Address => :5000
torrent_1  | Directory => exadir
torrent_1  | 
torrent_1  | [INFO] 2021/09/02 06:59:20 Torrent Client Created
torrent_1  | [INFO] 2021/09/02 06:59:20 Starting server on :5000
torrent_1  | [INFO] 2021/09/02 06:59:20 Adding Torrent
torrent_1  | [INFO] 2021/09/02 06:59:20 Getting Metainfo from Local Cache
torrent_1  | [INFO] 2021/09/02 06:59:20 Torrent Metainfo is not present in Cache file doesn't exist
torrent_1  | [INFO] 2021/09/02 06:59:20 Torrent Metainfo requested from Online Cache
torrent_1  | [INFO] 2021/09/02 06:59:20 Adding Torrent from Torrent URL  https://itorrents.org/torrent/787b951c9635c58928260e02a01e2b5434d8bb13.torrent
torrent_1  | [WARN] 2021/09/02 06:59:30 TrackerList URL:  https://ngosang.github.io/trackerslist/trackers_best.txt  is Invalid
torrent_1  | [INFO] 2021/09/02 06:59:30 Loaded  0  trackers in total , eliminating duplicates
torrent_1  | [INFO] 2021/09/02 06:59:30 Added Loaded Trackers to Torrents
torrent_1  | [INFO] 2021/09/02 06:59:44 User ystyle (172.20.0.1:44756) Connected
torrent_1  | [INFO] 2021/09/02 06:59:46 Starting gettorrents for  ystyle
torrent_1  | [INFO] 2021/09/02 06:59:51 Stopped gettorrents for  ystyle
torrent_1  | [INFO] 2021/09/02 06:59:51 Starting gettorrents for  ystyle
torrent_1  | [INFO] 2021/09/02 06:59:51 Stopped gettorrents for  ystyle
torrent_1  | [INFO] 2021/09/02 06:59:51 Stopped Stream for  ystyle
torrent_1  | [INFO] 2021/09/02 06:59:51 Starting gettorrentinfo for  ystyle
torrent_1  | [WARN] 2021/09/02 07:00:11 open exadir/torrents/787b951c9635c58928260e02a01e2b5434d8bb13: no such file or directory
torrent_1  | [WARN] 2021/09/02 07:00:13 open exadir/torrents/787b951c9635c58928260e02a01e2b5434d8bb13: no such file or directory
torrent_1  | [INFO] 2021/09/02 07:01:38 User ystyle (172.20.0.1:44756) Disconnected
torrent_1  | [ERR ] 2021/09/02 07:01:43 write tcp 172.20.0.2:5000->172.20.0.1:44756: use of closed network connection
torrent_1  | 
torrent_1  | [WARN] 2021/09/02 07:06:39 Recieved  terminated
torrent_1  | [WARN] 2021/09/02 07:06:40 Closing exatorrent
torrent_1  | [WARN] 2021/09/02 07:06:44 Torrent Client Closed! So,Torrent Not Started
exatorrent_torrent_1 exited with code 1

```
Picture of htop running for a period of time
![微信图片_20210902151328](https://user-images.githubusercontent.com/4478635/131799195-3048fc7e-835a-4b9c-9700-1462e5d649d1.jpg)

Picture before system suspended animation
![2021-09-02_15-14](https://user-images.githubusercontent.com/4478635/131799405-0cb17cf0-b8b3-4988-936c-c3bb7bf8e0d1.png)

**Comment by ystyle** [comment] 2021-09-02 07:22
### binary version
```log
ystyle@Archlinux  ~/Downloads  ./exatorrent-linux-amd64 

Address => :5000
Directory => exadir

[INFO] 2021/09/02 15:17:14 Adding Admin user with username "adminuser" and password "adminpassword"
[INFO] 2021/09/02 15:17:14 Torrent Client Created
[INFO] 2021/09/02 15:17:14 Starting server on :5000
[WARN] 2021/09/02 15:17:14 TrackerList URL:  https://ngosang.github.io/trackerslist/trackers_best.txt  is Invalid
[INFO] 2021/09/02 15:17:14 Loaded  0  trackers in total , eliminating duplicates
[INFO] 2021/09/02 15:17:14 Added Loaded Trackers to Torrents
[WARN] 2021/09/02 15:17:26 not authorized (127.0.0.1:60644)
[WARN] 2021/09/02 15:17:26 not authorized (127.0.0.1:60642)
[WARN] 2021/09/02 15:17:46 not authorized (127.0.0.1:60646)
[INFO] 2021/09/02 15:17:46 User adminuser (127.0.0.1:60642) Authenticated
[INFO] 2021/09/02 15:17:46 User adminuser (127.0.0.1:60648) Connected
[INFO] 2021/09/02 15:17:54 Adding Torrent
[INFO] 2021/09/02 15:17:54 Torrent:  787b951c9635c58928260e02a01e2b5434d8bb13  User:  adminuser
[INFO] 2021/09/02 15:17:54 Added Torrent to Torrent Database
[INFO] 2021/09/02 15:17:54 Getting Metainfo from Local Cache
[INFO] 2021/09/02 15:17:54 Torrent Metainfo is not present in Cache file doesn't exist
[INFO] 2021/09/02 15:17:54 Torrent Metainfo requested from Online Cache
[INFO] 2021/09/02 15:17:54 Adding Torrent from Torrent URL  https://itorrents.org/torrent/787b951c9635c58928260e02a01e2b5434d8bb13.torrent
[INFO] 2021/09/02 15:17:55 Starting gettorrents for  adminuser
[INFO] 2021/09/02 15:17:56 Torrent  787b951c9635c58928260e02a01e2b5434d8bb13  is Loaded
[INFO] 2021/09/02 15:17:56 Starting Torrent for Infohash  787b951c9635c58928260e02a01e2b5434d8bb13
[INFO] 2021/09/02 15:17:56 Torrent Metainfo merged form Online Cache
[INFO] 2021/09/02 15:17:56 Torrent  787b951c9635c58928260e02a01e2b5434d8bb13  Started by  adminuser
[INFO] 2021/09/02 15:17:56 created torrent cache file 787b951c9635c58928260e02a01e2b5434d8bb13
[INFO] 2021/09/02 15:18:00 Stopped gettorrents for  adminuser
[INFO] 2021/09/02 15:18:00 Starting gettorrents for  adminuser
[INFO] 2021/09/02 15:18:05 Stopped gettorrents for  adminuser
[INFO] 2021/09/02 15:18:05 Stopped Stream for  adminuser
[INFO] 2021/09/02 15:18:05 Starting gettorrentinfo for  adminuser
[UTP ] 2021/09/02 15:18:57 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:00 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:04 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:07 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:24 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:27 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:28 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
[INFO] 2021/09/02 15:19:35 Stopped gettorrentinfo for  adminuser
[INFO] 2021/09/02 15:19:35 Stopped Stream for  adminuser
[INFO] 2021/09/02 15:19:35 Starting gettorrents for  adminuser
[INFO] 2021/09/02 15:19:35 Stopped gettorrents for  adminuser
[INFO] 2021/09/02 15:19:35 Starting gettorrents for  adminuser
[UTP ] 2021/09/02 15:19:41 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:41 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:44 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:44 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:46 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:46 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:49 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:49 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:52 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:53 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:55 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:56 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:19:59 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:00 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:02 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:03 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:19 error sending packet: write udp6 [::]:42069->[2001:fb1:df:f3c2:c035:9ea:7029:3ca]:64994: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:22 error sending packet: write udp6 [::]:42069->[2001:fb1:df:f3c2:c035:9ea:7029:3ca]:64994: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:26 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:30 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
[UTP ] 2021/09/02 15:20:33 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable

```

![2021-09-02_15-20](https://user-images.githubusercontent.com/4478635/131800340-def2b607-60f3-420e-9b87-8c0ee73ffb71.png)

Waited a few minutes, it looks normal

**Comment by varbhat** [comment] 2021-09-02 07:33
> ### binary version
> 
> ```
> ystyle@Archlinux  ~/Downloads  ./exatorrent-linux-amd64 
> 
> Address => :5000
> Directory => exadir
> 
> [INFO] 2021/09/02 15:17:14 Adding Admin user with username "adminuser" and password "adminpassword"
> [INFO] 2021/09/02 15:17:14 Torrent Client Created
> [INFO] 2021/09/02 15:17:14 Starting server on :5000
> [WARN] 2021/09/02 15:17:14 TrackerList URL:  https://ngosang.github.io/trackerslist/trackers_best.txt  is Invalid
> [INFO] 2021/09/02 15:17:14 Loaded  0  trackers in total , eliminating duplicates
> [INFO] 2021/09/02 15:17:14 Added Loaded Trackers to Torrents
> [WARN] 2021/09/02 15:17:26 not authorized (127.0.0.1:60644)
> [WARN] 2021/09/02 15:17:26 not authorized (127.0.0.1:60642)
> [WARN] 2021/09/02 15:17:46 not authorized (127.0.0.1:60646)
> [INFO] 2021/09/02 15:17:46 User adminuser (127.0.0.1:60642) Authenticated
> [INFO] 2021/09/02 15:17:46 User adminuser (127.0.0.1:60648) Connected
> [INFO] 2021/09/02 15:17:54 Adding Torrent
> [INFO] 2021/09/02 15:17:54 Torrent:  787b951c9635c58928260e02a01e2b5434d8bb13  User:  adminuser
> [INFO] 2021/09/02 15:17:54 Added Torrent to Torrent Database
> [INFO] 2021/09/02 15:17:54 Getting Metainfo from Local Cache
> [INFO] 2021/09/02 15:17:54 Torrent Metainfo is not present in Cache file doesn't exist
> [INFO] 2021/09/02 15:17:54 Torrent Metainfo requested from Online Cache
> [INFO] 2021/09/02 15:17:54 Adding Torrent from Torrent URL  https://itorrents.org/torrent/787b951c9635c58928260e02a01e2b5434d8bb13.torrent
> [INFO] 2021/09/02 15:17:55 Starting gettorrents for  adminuser
> [INFO] 2021/09/02 15:17:56 Torrent  787b951c9635c58928260e02a01e2b5434d8bb13  is Loaded
> [INFO] 2021/09/02 15:17:56 Starting Torrent for Infohash  787b951c9635c58928260e02a01e2b5434d8bb13
> [INFO] 2021/09/02 15:17:56 Torrent Metainfo merged form Online Cache
> [INFO] 2021/09/02 15:17:56 Torrent  787b951c9635c58928260e02a01e2b5434d8bb13  Started by  adminuser
> [INFO] 2021/09/02 15:17:56 created torrent cache file 787b951c9635c58928260e02a01e2b5434d8bb13
> [INFO] 2021/09/02 15:18:00 Stopped gettorrents for  adminuser
> [INFO] 2021/09/02 15:18:00 Starting gettorrents for  adminuser
> [INFO] 2021/09/02 15:18:05 Stopped gettorrents for  adminuser
> [INFO] 2021/09/02 15:18:05 Stopped Stream for  adminuser
> [INFO] 2021/09/02 15:18:05 Starting gettorrentinfo for  adminuser
> [UTP ] 2021/09/02 15:18:57 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:00 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:04 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:07 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:24 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:27 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:28 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
> [INFO] 2021/09/02 15:19:35 Stopped gettorrentinfo for  adminuser
> [INFO] 2021/09/02 15:19:35 Stopped Stream for  adminuser
> [INFO] 2021/09/02 15:19:35 Starting gettorrents for  adminuser
> [INFO] 2021/09/02 15:19:35 Stopped gettorrents for  adminuser
> [INFO] 2021/09/02 15:19:35 Starting gettorrents for  adminuser
> [UTP ] 2021/09/02 15:19:41 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:41 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:44 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:44 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:46 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:46 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:49 error sending packet: write udp6 [::]:42069->[2601:802:8200:3220:8e1:5d86:47a9:47a0]:4385: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:49 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:2155:2fb3:4f1f:7072]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:52 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:53 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:55 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:56 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:19:59 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:00 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:02 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:9007:d36c:9084:ed21]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:03 error sending packet: write udp6 [::]:42069->[2001:da8:e000:7274:de7:dfb1:5b2b:f9c4]:23938: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:19 error sending packet: write udp6 [::]:42069->[2001:fb1:df:f3c2:c035:9ea:7029:3ca]:64994: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:22 error sending packet: write udp6 [::]:42069->[2001:fb1:df:f3c2:c035:9ea:7029:3ca]:64994: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:26 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:30 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
> [UTP ] 2021/09/02 15:20:33 error sending packet: write udp6 [::]:42069->[2409:8a74:2683:d940:a0d5:aa33:8d22:6e62]:8113: sendto: network is unreachable
> ```
> 
> ![2021-09-02_15-20](https://user-images.githubusercontent.com/4478635/131800340-def2b607-60f3-420e-9b87-8c0ee73ffb71.png)
> 
> Waited a few minutes, it looks normal

Ok. Looks like problem with Docker not with exatorrent . I cannot say that it's issue of exatorrent Docker image because many are using Docker image of exatorrent without any issue .

You can try maybe with Podman and check if problem exists. 

Closing this issue for now. Re-open if issue exists

**Closed by varbhat** 2021-09-02 07:33 UTC

**Comment by ystyle** [comment] 2021-09-02 07:34
> ![image](https://user-images.githubusercontent.com/68165364/131801449-9d882caf-e975-42d7-9d44-a16de314a84d.png)
> 
> ![image](https://user-images.githubusercontent.com/68165364/131800990-3ecfe236-cae9-4bc5-b602-af650837ce74.png)
> 
> ![image](https://user-images.githubusercontent.com/68165364/131801093-69d57fb1-4bf1-4654-9b86-ee3f1e81e89e.png)
> 
> @ystyle ,
> I couldn't reproduce what you said . It's running normal with the said torrent of yours . I am not running in Docker

Yes, now it seems to only happen in docker

**Comment by Kuinox** [comment] 2022-04-05 19:59
Hi, I have the same issue, running from docker.
Docker is most likely not the cause of this issue, but helps triggering a bug in your app.
